version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: email_marketing_db
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"        # drop in CI/prod if not needed
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --sql_mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  seed:
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile
    env_file: .env
    command: ["python", "scripts/seed_db.py"]
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}

  # fastapi:
  #   build:
  #     context: .
  #     dockerfile: docker/fastapi/Dockerfile
  #   env_file: .env
  #   command: ["uvicorn", "apps.fastapi_app.main:app", "--host", "0.0.0.0", "--port", "8000"]
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   ports:
  #     - "8000:8000"

volumes:
  db_data:
